local BallGui = Instance.new("ScreenGui")
BallGui.Name = "8BallGui"
BallGui.ResetOnSpawn = false
BallGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
BallGui.DisplayOrder = 9990
BallGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local BallText = Instance.new("TextLabel")
BallText.Name = "BallText"
BallText.Position = UDim2.new(0.5, 0, 1, -10)
BallText.Size = UDim2.new(0, 80, 0, 30)
BallText.BackgroundColor3 = Color3.new(0, 0, 0)
BallText.BorderSizePixel = 0
BallText.BorderColor3 = Color3.new(0, 0, 0)
BallText.ZIndex = 2
BallText.AnchorPoint = Vector2.new(0.5, 1)
BallText.Text = "Ball x"
BallText.TextColor3 = Color3.new(1, 1, 1)
BallText.TextSize = 14
BallText.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
BallText.TextScaled = true
BallText.TextWrapped = true
BallText.Parent = BallGui

local UIStroke = Instance.new("UIStroke")
UIStroke.Name = "UIStroke"
UIStroke.Color = Color3.new(1, 1, 1)
UIStroke.Thickness = 2
UIStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke.Parent = BallText

local BackBall = Instance.new("TextButton")
BackBall.Name = "BackBall"
BackBall.Position = UDim2.new(0.5, -70, 1, -10)
BackBall.Size = UDim2.new(0, 30, 0, 30)
BackBall.BackgroundColor3 = Color3.new(0.196078, 0, 0)
BackBall.BorderSizePixel = 0
BackBall.BorderColor3 = Color3.new(0, 0, 0)
BackBall.AnchorPoint = Vector2.new(0.5, 1)
BackBall.Text = "<"
BackBall.TextColor3 = Color3.new(1, 1, 1)
BackBall.TextSize = 14
BackBall.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
BackBall.TextScaled = true
BackBall.TextWrapped = true
BackBall.Parent = BallGui

local UIStroke2 = Instance.new("UIStroke")
UIStroke2.Name = "UIStroke"
UIStroke2.Color = Color3.new(1, 0, 0)
UIStroke2.Thickness = 2
UIStroke2.Transparency = 0.25
UIStroke2.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke2.Parent = BackBall

local GuideKeyPC = Instance.new("TextLabel")
GuideKeyPC.Name = "GuideKeyPC"
GuideKeyPC.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC.BackgroundTransparency = 1
GuideKeyPC.BorderSizePixel = 0
GuideKeyPC.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC.Transparency = 1
GuideKeyPC.Text = "Q"
GuideKeyPC.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC.TextSize = 14
GuideKeyPC.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC.TextScaled = true
GuideKeyPC.TextWrapped = true
GuideKeyPC.Parent = BackBall

local NextBall = Instance.new("TextButton")
NextBall.Name = "NextBall"
NextBall.Position = UDim2.new(0.5, 70, 1, -10)
NextBall.Size = UDim2.new(0, 30, 0, 30)
NextBall.BackgroundColor3 = Color3.new(0, 0.196078, 0)
NextBall.BorderSizePixel = 0
NextBall.BorderColor3 = Color3.new(0, 0, 0)
NextBall.AnchorPoint = Vector2.new(0.5, 1)
NextBall.Text = ">"
NextBall.TextColor3 = Color3.new(1, 1, 1)
NextBall.TextSize = 14
NextBall.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
NextBall.TextScaled = true
NextBall.TextWrapped = true
NextBall.Parent = BallGui

local UIStroke3 = Instance.new("UIStroke")
UIStroke3.Name = "UIStroke"
UIStroke3.Color = Color3.new(0, 1, 0)
UIStroke3.Thickness = 2
UIStroke3.Transparency = 0.25
UIStroke3.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke3.Parent = NextBall

local GuideKeyPC2 = Instance.new("TextLabel")
GuideKeyPC2.Name = "GuideKeyPC"
GuideKeyPC2.Position = UDim2.new(1, 0, 0, 0)
GuideKeyPC2.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC2.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC2.BackgroundTransparency = 1
GuideKeyPC2.BorderSizePixel = 0
GuideKeyPC2.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC2.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC2.Transparency = 1
GuideKeyPC2.Text = "E"
GuideKeyPC2.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC2.TextSize = 14
GuideKeyPC2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC2.TextScaled = true
GuideKeyPC2.TextWrapped = true
GuideKeyPC2.Parent = NextBall

local RotationL = Instance.new("ImageButton")
RotationL.Name = "RotationL"
RotationL.Position = UDim2.new(0.5, -70, 1, -10)
RotationL.Size = UDim2.new(0, 30, 0, 30)
RotationL.BackgroundColor3 = Color3.new(0.196078, 0, 0)
RotationL.BorderSizePixel = 0
RotationL.BorderColor3 = Color3.new(0, 0, 0)
RotationL.AnchorPoint = Vector2.new(0.5, 1)
RotationL.Image = "rbxassetid://99144149703689"
RotationL.Parent = BallGui

local UIStroke4 = Instance.new("UIStroke")
UIStroke4.Name = "UIStroke"
UIStroke4.Color = Color3.new(1, 0, 0)
UIStroke4.Thickness = 2
UIStroke4.Transparency = 0.25
UIStroke4.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke4.Parent = RotationL

local GuideKeyPC3 = Instance.new("TextLabel")
GuideKeyPC3.Name = "GuideKeyPC"
GuideKeyPC3.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC3.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC3.BackgroundTransparency = 1
GuideKeyPC3.BorderSizePixel = 0
GuideKeyPC3.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC3.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC3.Transparency = 1
GuideKeyPC3.Text = "Q"
GuideKeyPC3.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC3.TextSize = 14
GuideKeyPC3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC3.TextScaled = true
GuideKeyPC3.TextWrapped = true
GuideKeyPC3.Parent = RotationL

local RotationR = Instance.new("ImageButton")
RotationR.Name = "RotationR"
RotationR.Position = UDim2.new(0.5, 70, 1, -10)
RotationR.Size = UDim2.new(0, 30, 0, 30)
RotationR.BackgroundColor3 = Color3.new(0, 0.196078, 0)
RotationR.BorderSizePixel = 0
RotationR.BorderColor3 = Color3.new(0, 0, 0)
RotationR.AnchorPoint = Vector2.new(0.5, 1)
RotationR.Image = "rbxassetid://105326449283697"
RotationR.Parent = BallGui

local UIStroke5 = Instance.new("UIStroke")
UIStroke5.Name = "UIStroke"
UIStroke5.Color = Color3.new(0, 1, 0)
UIStroke5.Thickness = 2
UIStroke5.Transparency = 0.25
UIStroke5.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke5.Parent = RotationR

local GuideKeyPC4 = Instance.new("TextLabel")
GuideKeyPC4.Name = "GuideKeyPC"
GuideKeyPC4.Position = UDim2.new(1, 0, 0, 0)
GuideKeyPC4.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC4.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC4.BackgroundTransparency = 1
GuideKeyPC4.BorderSizePixel = 0
GuideKeyPC4.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC4.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC4.Transparency = 1
GuideKeyPC4.Text = "E"
GuideKeyPC4.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC4.TextSize = 14
GuideKeyPC4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC4.TextScaled = true
GuideKeyPC4.TextWrapped = true
GuideKeyPC4.Parent = RotationR

local RotationMode = Instance.new("TextButton")
RotationMode.Name = "RotationMode"
RotationMode.Position = UDim2.new(0.5, 150, 1, -10)
RotationMode.Size = UDim2.new(0, 70, 0, 30)
RotationMode.BackgroundColor3 = Color3.new(0.196078, 0, 0)
RotationMode.BorderSizePixel = 0
RotationMode.BorderColor3 = Color3.new(0, 0, 0)
RotationMode.AnchorPoint = Vector2.new(0.5, 1)
RotationMode.Text = "Rotation mode"
RotationMode.TextColor3 = Color3.new(1, 1, 1)
RotationMode.TextSize = 14
RotationMode.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
RotationMode.TextScaled = true
RotationMode.TextWrapped = true
RotationMode.Parent = BallGui

local UIStroke6 = Instance.new("UIStroke")
UIStroke6.Name = "UIStroke"
UIStroke6.Color = Color3.new(1, 0, 0)
UIStroke6.Thickness = 2
UIStroke6.Transparency = 0.25
UIStroke6.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke6.Parent = RotationMode

local GuideKeyPC5 = Instance.new("TextLabel")
GuideKeyPC5.Name = "GuideKeyPC"
GuideKeyPC5.Position = UDim2.new(1, 0, 0, 0)
GuideKeyPC5.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC5.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC5.BackgroundTransparency = 1
GuideKeyPC5.BorderSizePixel = 0
GuideKeyPC5.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC5.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC5.Transparency = 1
GuideKeyPC5.Text = "G"
GuideKeyPC5.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC5.TextSize = 14
GuideKeyPC5.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC5.TextScaled = true
GuideKeyPC5.TextWrapped = true
GuideKeyPC5.Parent = RotationMode

local CueLine = Instance.new("TextButton")
CueLine.Name = "CueLine"
CueLine.Position = UDim2.new(0.5, -150, 1, -10)
CueLine.Size = UDim2.new(0, 70, 0, 30)
CueLine.BackgroundColor3 = Color3.new(0.392157, 0.392157, 0.392157)
CueLine.BorderSizePixel = 0
CueLine.BorderColor3 = Color3.new(0, 0, 0)
CueLine.AnchorPoint = Vector2.new(0.5, 1)
CueLine.Text = "Cue line [off]"
CueLine.TextColor3 = Color3.new(1, 1, 1)
CueLine.TextSize = 14
CueLine.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
CueLine.TextScaled = true
CueLine.TextWrapped = true
CueLine.Parent = BallGui

local StripesUI = Instance.new("UIGradient")
StripesUI.Name = "StripesUI"
StripesUI.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.new(0.0941176, 0.427451, 0.784314)), ColorSequenceKeypoint.new(0.25, Color3.new(0.175582, 0.478939, 0.80371)), ColorSequenceKeypoint.new(0.251, Color3.new(1, 1, 1)), ColorSequenceKeypoint.new(0.5, Color3.new(1, 1, 1)), ColorSequenceKeypoint.new(0.749, Color3.new(1, 1, 1)), ColorSequenceKeypoint.new(0.75, Color3.new(0.211882, 0.501882, 0.812353)), ColorSequenceKeypoint.new(1, Color3.new(0.0941176, 0.427451, 0.784314))})
StripesUI.Rotation = 90
StripesUI.Enabled = false
StripesUI.Parent = CueLine

local UIStroke7 = Instance.new("UIStroke")
UIStroke7.Name = "UIStroke"
UIStroke7.Color = Color3.new(1, 1, 1)
UIStroke7.Thickness = 2
UIStroke7.Transparency = 0.25
UIStroke7.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke7.Parent = CueLine

local GuideKeyPC6 = Instance.new("TextLabel")
GuideKeyPC6.Name = "GuideKeyPC"
GuideKeyPC6.Position = UDim2.new(1, 0, 0, 0)
GuideKeyPC6.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC6.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC6.BackgroundTransparency = 1
GuideKeyPC6.BorderSizePixel = 0
GuideKeyPC6.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC6.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC6.Transparency = 1
GuideKeyPC6.Text = "H"
GuideKeyPC6.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC6.TextSize = 14
GuideKeyPC6.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC6.TextScaled = true
GuideKeyPC6.TextWrapped = true
GuideKeyPC6.Parent = CueLine

local GuideRotation = Instance.new("TextLabel")
GuideRotation.Name = "GuideRotation"
GuideRotation.Position = UDim2.new(0.5, 0, 1, -50)
GuideRotation.Size = UDim2.new(0, 200, 0, 20)
GuideRotation.BackgroundColor3 = Color3.new(1, 1, 1)
GuideRotation.BackgroundTransparency = 1
GuideRotation.BorderSizePixel = 0
GuideRotation.BorderColor3 = Color3.new(0, 0, 0)
GuideRotation.AnchorPoint = Vector2.new(0.5, 1)
GuideRotation.Transparency = 1
GuideRotation.Text = "Hold <b>Shift</b> to slow rotation"
GuideRotation.TextColor3 = Color3.new(1, 1, 1)
GuideRotation.TextSize = 14
GuideRotation.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
GuideRotation.TextScaled = true
GuideRotation.TextWrapped = true
GuideRotation.RichText = true
GuideRotation.Parent = BallGui

local RotationCueR = Instance.new("ImageButton")
RotationCueR.Name = "RotationCueR"
RotationCueR.Position = UDim2.new(0.5, -210, 1, -10)
RotationCueR.Size = UDim2.new(0, 30, 0, 30)
RotationCueR.BackgroundColor3 = Color3.new(0, 0.196078, 0)
RotationCueR.BorderSizePixel = 0
RotationCueR.BorderColor3 = Color3.new(0, 0, 0)
RotationCueR.AnchorPoint = Vector2.new(0.5, 1)
RotationCueR.Image = "rbxassetid://105326449283697"
RotationCueR.Parent = BallGui

local UIStroke8 = Instance.new("UIStroke")
UIStroke8.Name = "UIStroke"
UIStroke8.Color = Color3.new(0, 1, 0)
UIStroke8.Thickness = 2
UIStroke8.Transparency = 0.25
UIStroke8.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke8.Parent = RotationCueR

local GuideKeyPC7 = Instance.new("TextLabel")
GuideKeyPC7.Name = "GuideKeyPC"
GuideKeyPC7.Position = UDim2.new(1, 0, 0, 0)
GuideKeyPC7.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC7.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC7.BackgroundTransparency = 1
GuideKeyPC7.BorderSizePixel = 0
GuideKeyPC7.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC7.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC7.Transparency = 1
GuideKeyPC7.Text = "X"
GuideKeyPC7.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC7.TextSize = 14
GuideKeyPC7.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC7.TextScaled = true
GuideKeyPC7.TextWrapped = true
GuideKeyPC7.Parent = RotationCueR

local RotationCueL = Instance.new("ImageButton")
RotationCueL.Name = "RotationCueL"
RotationCueL.Position = UDim2.new(0.5, -250, 1, -10)
RotationCueL.Size = UDim2.new(0, 30, 0, 30)
RotationCueL.BackgroundColor3 = Color3.new(0.196078, 0, 0)
RotationCueL.BorderSizePixel = 0
RotationCueL.BorderColor3 = Color3.new(0, 0, 0)
RotationCueL.AnchorPoint = Vector2.new(0.5, 1)
RotationCueL.Image = "rbxassetid://99144149703689"
RotationCueL.Parent = BallGui

local UIStroke9 = Instance.new("UIStroke")
UIStroke9.Name = "UIStroke"
UIStroke9.Color = Color3.new(1, 0, 0)
UIStroke9.Thickness = 2
UIStroke9.Transparency = 0.25
UIStroke9.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke9.Parent = RotationCueL

local GuideKeyPC8 = Instance.new("TextLabel")
GuideKeyPC8.Name = "GuideKeyPC"
GuideKeyPC8.Size = UDim2.new(0.75, 0, 0.75, 0)
GuideKeyPC8.BackgroundColor3 = Color3.new(1, 1, 1)
GuideKeyPC8.BackgroundTransparency = 1
GuideKeyPC8.BorderSizePixel = 0
GuideKeyPC8.BorderColor3 = Color3.new(0, 0, 0)
GuideKeyPC8.AnchorPoint = Vector2.new(0.5, 0.5)
GuideKeyPC8.Transparency = 1
GuideKeyPC8.Text = "Z"
GuideKeyPC8.TextColor3 = Color3.new(1, 1, 1)
GuideKeyPC8.TextSize = 14
GuideKeyPC8.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
GuideKeyPC8.TextScaled = true
GuideKeyPC8.TextWrapped = true
GuideKeyPC8.Parent = RotationCueL

for _,v in ipairs(BallGui:GetDescendants()) do
	if v:IsA("TextLabel") or v:IsA("TextButton") or v:IsA("TextBox") then
		v.TextTransparency = 0
        v.TextStrokeTransparency = 0
	end
end
